### ISSUE TITLE
Eixo 3 - atualização de números

### ISSUE THREAD

**Issue by camilacauzzi** [Neccult/atlasOBEC#103]
Os valores de algumas variáveis foram atualizados para o índice de inflação de 2017, o que implica que os números mudaram. Nem todas as variáveis foram atualizadas, pois algumas não necessitavam de correção pela inflação. Abaixo, as variáveis que devem ser atualizadas na plataforma, com os respectivos links para o Drive:

[OK] V1 - Financiamento total (e todas suas desagregações): [https://drive.google.com/file/d/1tOcI6jCGEIBI8PKSf3T0HcbDrQMPggZt/view?usp=sharing](https://drive.google.com/file/d/1tOcI6jCGEIBI8PKSf3T0HcbDrQMPggZt/view?usp=sharing)
[OK] V3 - Financiamento do BNDES: [https://drive.google.com/file/d/1P_OPCTvNaGFKPgUElw9QwpofcPz_9nJn/view?usp=sharing](https://drive.google.com/file/d/1tOcI6jCGEIBI8PKSf3T0HcbDrQMPggZt/view?usp=sharing)
V4 - Incentivos privados: [https://drive.google.com/file/d/175FnZMtk1cPuDuuCibmCaO7zl8mpcWk3/view?usp=sharing](https://drive.google.com/file/d/175FnZMtk1cPuDuuCibmCaO7zl8mpcWk3/view?usp=sharing)
V5 - Incentivos públicos: [https://drive.google.com/file/d/1vGSy8PfAyCHCIebsrTFEZ6dAx5pp_ZSX/view?usp=sharing](https://drive.google.com/file/d/1vGSy8PfAyCHCIebsrTFEZ6dAx5pp_ZSX/view?usp=sharing)
[OK] V8 - Financiamento / VA: [https://drive.google.com/file/d/1U54AAOFGeui-PdbPJ-oP-sERtLB_Pv9H/view?usp=sharing](https://drive.google.com/file/d/1U54AAOFGeui-PdbPJ-oP-sERtLB_Pv9H/view?usp=sharing)
[OK] V9 - Financiamento / massa salarial: [https://drive.google.com/file/d/1EyVzYgl_WzTj6Xxjxjwzy2ObxCtKt82o/view?usp=sharing](https://drive.google.com/file/d/1EyVzYgl_WzTj6Xxjxjwzy2ObxCtKt82o/view?usp=sharing)
V15 - C4: [https://drive.google.com/file/d/1zwKsnOLEayZGWqKP88JoFzbSASEyzvdd/view?usp=sharing](https://drive.google.com/file/d/1zwKsnOLEayZGWqKP88JoFzbSASEyzvdd/view?usp=sharing)
V16 - IHH: [https://drive.google.com/file/d/1OFcPEvglHN46_kC205kODbsfz1tuuBSW/view?usp=sharing](https://drive.google.com/file/d/1OFcPEvglHN46_kC205kODbsfz1tuuBSW/view?usp=sharing)

**Comment by camilacauzzi** [comment]
Conforme solicitado, variáveis foram atualizadas para conter a coluna "Cultura" no final.

Novos links para a V4  e a V5 (como arquivo é muito grande, houve problema de carregamento, então tive que salvar novamente):

V4 - Incentivos privados: [https://drive.google.com/file/d/1_IFSj3oAnblVxzwlXDndvyRCTPpJgY4I/view?usp=sharing](https://drive.google.com/file/d/1_IFSj3oAnblVxzwlXDndvyRCTPpJgY4I/view?usp=sharing)

V5 - Incentivos públicos: [https://drive.google.com/file/d/1oSsY0t9rWrkiOPSiulfj8N7WaEEAYPy9/view?usp=sharing](https://drive.google.com/file/d/1oSsY0t9rWrkiOPSiulfj8N7WaEEAYPy9/view?usp=sharing)

As demais variáveis foram atualizadas nos links antigos.

**Comment by camilacauzzi** [comment]
Link correto para a V3: [https://drive.google.com/file/d/1P_OPCTvNaGFKPgUElw9QwpofcPz_9nJn/view?usp=sharing](https://drive.google.com/file/d/1P_OPCTvNaGFKPgUElw9QwpofcPz_9nJn/view?usp=sharing)

**Comment by camilacauzzi** [comment]
Atualizar dados das seguintes variáveis (e respectivos links para os arquivos em Excel):

V1: [FINANCIAMENTO PÚBLICO TOTAL](https://drive.google.com/file/d/1SMxWt_L4Y9YbYb_kUFpdpvfI8cDQrrcQ/view?usp=sharing)
V8: [PARTICIPAÇÃO DO FINANCIAMENTO PÚBLICO TOTAL NO VALOR ADICIONADO PELAS ATIVIDADES CULTURAIS](https://drive.google.com/file/d/1U54AAOFGeui-PdbPJ-oP-sERtLB_Pv9H/view?usp=sharing)
V9: [PARTICIPAÇÃO DO VALOR TOTAL BRUTO EM FOMENTO À CULTURA NA MASSA SALARIAL DAS ATIVIDADES CULTURAIS](https://drive.google.com/file/d/1EyVzYgl_WzTj6Xxjxjwzy2ObxCtKt82o/view?usp=sharing)
V15: [ÍNDICE RAZÃO PARA CONCENTRAÇÃO DOS INCENTIVOS FISCAIS (C4)](https://drive.google.com/file/d/1zwKsnOLEayZGWqKP88JoFzbSASEyzvdd/view?usp=sharing)
V16: [ÍNDICE HERFINDAHL-HIRSCHMAN PARA CONCENTRAÇÃO DOS PROJETOS FOMENTADOS](https://drive.google.com/file/d/1OFcPEvglHN46_kC205kODbsfz1tuuBSW/view?usp=sharing)

**Comment by gustavomoller** [comment]
Camila, as tabelas das variáveis V4 e V5 não estão abrindo. Favor verificar.

**Comment by camilacauzzi** [comment]
Links para V4 e V5 em tabelas menos pesadas:

V4: [https://drive.google.com/file/d/0BwJjOwdgA5r2cFM3SGl4ZklKYVgxLVV6Y1RxS0U5TlA1MXIw/view?usp=sharing](https://drive.google.com/file/d/0BwJjOwdgA5r2cFM3SGl4ZklKYVgxLVV6Y1RxS0U5TlA1MXIw/view?usp=sharing)

V5: [https://drive.google.com/file/d/1v4d1LKiLxcvbCGbSBNgUmND6lufgjsbv/view?usp=sharing](https://drive.google.com/file/d/1v4d1LKiLxcvbCGbSBNgUmND6lufgjsbv/view?usp=sharing)
