### ISSUE TITLE
Eixo 1 - Variável 1- Total de trabalhadores

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#110]
- [OK] Quando selecionado o porte e um setor e/ou UF, os números do mapa não batem com o que é mostrado no box de dados
![captura de tela 2018-04-26 as 18 45 22](https://user-images.githubusercontent.com/35271320/39333681-16d400dc-4982-11e8-9e56-80cb13e02f86.png)

- Treemap setores não corresponde aos dados corretamente. Treemap não atualiza corretamente com relação aos Estados. Os Estados que tem mais erros são aqueles em que o número de empresas de porte médio é zero.

**Comment by gustavomoller** [comment]
- Quando somente uma UF está selecionada, a legenda de dados de porcentagem deve ser DO BRASIL, ao invés da UF

![image](https://user-images.githubusercontent.com/35271320/39440164-70bd5ea8-4c80-11e8-9655-490c2778c98c.png)

**Comment by leodorna** [comment]
O problema do Treemap de setores é que ele faz uma proporção entre os setores a partir da desagregação +  ano + estado. Por exemplo: 
se eu selecionar Mato Grosso com Porte Micro para o ano 2016, a porcentagem de cada setor do Treemap representa a proporção de cada setor entre empresas **de porte micro** para o ano de 2016 **do estado de Mato Grosso.**

**Comment by leodorna** [comment]
Isso ocasiona problemas na descrição de porcentagem, já que quando selecionado um Setor, o dado percentual utiliza a proporção do Treemap

**Comment by gustavomoller** [comment]
Ok, resolvemos isso com o issue sobre os dados no box de dados. Pode deixar como está
