### ISSUE TITLE
[OK] Eixo 1 - Variável 3 - Variação no total de empresas

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#112]
- [OK] Quando selecionado uma UF que possui variações iguais a zero em determinados anos, ao invés de seguir a serie histórica de variações, o gráfico agrupa todas as variações nos primeiros anos, ocasionando erro. Isso afeta também o gráfico de linhas
![captura de tela 2018-04-26 as 19 03 40](https://user-images.githubusercontent.com/35271320/39334344-9efb2a1a-4984-11e8-9e04-76083dd1a17d.png)

- [OK]  As variações iguais a zero não estão aparecendo no mapa.

- [OK] As variações mostram valores que não são compatíveis com a base de dados, além do problema já citado de que quando temos uma variação igual a zero, os dados subsequentes são puxados para esse anos que não tiveram variação.

- [OK] Gráfico de linhas não apresenta variações negativas e não estão em variação percentual. Consertar ambos.

**Comment by leodorna** [comment]
consertamos isso : "As variações iguais a zero não estão aparecendo no mapa."
