### ISSUE TITLE
[OK] Eixo 1 -  Variável 9 - Valor adicionado pelo PIB

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#119]
- [OK]A escala da série histórica está errada
![image](https://user-images.githubusercontent.com/35271320/39441585-d1f898c8-4c84-11e8-960e-524dd379e0a7.png)

- Os valores quando selecionada a UF e/ou setor devem ser multiplicados por 100

- [OK] No gráfico de linhas, não aparece o valor para alguns setores
![image](https://user-images.githubusercontent.com/35271320/39441757-55a8b8ec-4c85-11e8-99d7-84b0ba81d094.png)

**Comment by gustavomoller** [comment]
Retirar o treemap de UFs da visualização 

Colocar o gráfico de linhas quando não estiver selecionado nem UF, nem setor.

**Comment by xfrigo** [comment]
Valores pra quando UF E Setor selecionados foram multiplicados por 100.
Pra quando for somente UF sem setor selecionado também multiplicar?

**Comment by gustavomoller** [comment]
sim, multiplicar quando for só UF

**Comment by marcusvinicus** [comment]
O eixo vertical esta cortando os números
