### ISSUE TITLE
[ok] Eixo 2 - Geral - Menu desagregação

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#124]
- O menu de desagregações deve contar as opções de desagregação para escolha

1. Setorial
![image](https://user-images.githubusercontent.com/35271320/39524735-51847078-4df0-11e8-8127-f7e061af3b21.png)

a. Por porte
- Micro
- Pequena
- Média 
- Grande

b. Por sexo
- Feminino
- Marculino

c. Por idade
- 10 - 17 
- 18 - 29
- 30 - 49
- 50 - 64
- 65 ou mais

d. Por escolaridade
- Fundamental Incompleto
- Fundamental Completo
- Médio completo
- Superior incompleto
- Superior completo

2. Ocupacional
![image](https://user-images.githubusercontent.com/35271320/39525066-55dbbb9e-4df1-11e8-8aeb-c55286be16d8.png)

a. Por idade
- 10 - 17 
- 18 - 29
- 30 - 49
- 50 - 64
- 65 ou mais

b. Por escolaridade
- Sem instrução
- Fundamental Incompleto
- Fundamental Completo
- Médio completo
- Superior incompleto
- Superior completo
- Não determinado

c. Por cor
- Branca
- Parda
- Preta
- Amarela

d. Por formalidade
- Formal
- Informal

e. Por previdência
- Com Previdência 
- Sem previdência

f. Por sindicato
- Sindicalizado
- Não sindicalizado

**Comment by leodorna** [comment]
Comecei a mexer nisso, mas não to atualizando no ufrgs.br porque vou ter que mexer em alguns detalhes estruturais, então to fazendo separado.
