### ISSUE TITLE
[OK] Eixo 2 - Variável 3 - Remuneração Média

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#128]
- Quando selecionada uma desagregação, mostrar no gráfico de barras o valor da desagregação selecionada.

Ex: selecionado sexo feminino, colocar somente os valor para sexo feminino

- Quando muda a UF sem com a desagregação selecionada, o valor não muda.
![image](https://user-images.githubusercontent.com/35271320/39535151-947e467e-4e09-11e8-8210-ece74e845050.png)

- Os valores que deveriam ser zero em alguns anos estão igual a 7

**Comment by gustavomoller** [comment]
O gráfico de linhas do ocupacional não faz sentido

![image](https://user-images.githubusercontent.com/35271320/39537469-0c11cb9c-4e10-11e8-962f-6bf66379539d.png)

**Comment by leodorna** [comment]
[anotação] O gráfico de linhas do ocupacional é só uma linha para a desagregação ESCOLHER porque o gráfico está configurado para mostrar todas desagregações dentre o grupo de desagregações
