### ISSUE TITLE
Eixo 1 - Novo descritivo dos dados para box

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#139]
Obs: o valor que é descrito primeiro é o que deve ficar em destaque no box.

1. Total de empresas (MODELO VÁLIDO PARA VARIÁVEIS 1, 4, 5, 6, 7, 8, 9)
- Quando selecionado todos os setores e todas as UFs - Dois dados [VALOR DA SÉRIE HISTÓRICA] Empresas culturais e Criativas; [100%] das empresas culturais e criativas do Brasil
- Quanto selecionado alguma UF - [VALOR MAPA/SÉRIE HISTÓRICA] empresas culturais e criativas; [PORCENTAGEM TREEMAP UF] do total de empresas culturais e criativas do Brasil
- Quanto selecionado um setor - [VALOR DA SÉRIE HISTÓRICA] empresas do SETOR SELECIONADO, PORCENTAGEM TREEMAP SETORES] do total de empresas culturais e criativas do Brasil
- Quando um setor e uma UF selecionados: [VALOR SÉRIE HISTÓRICA/MAPA] de empresas DO SETOR SELECIONADO em/na UF; [PORCENTAGEM TREEMAP SETORES] do total de empresas culturais e criativas de/da UF selecionada; [PORCENTAGEM TREEMAP UF] do total de empresas do SETOR SELECIONADO no Brasil
- Quando selecionado um porte - [VALOR SÉRIE HISTÓRICA] empresas culturais e criativas de (PORTE SELECIONADO]; [PORCENTAGEM] do total de empresas culturais e criativas do Brasil.
- Quando selecionado um porte e um setor - [VALOR DA SÉRIE HISTÓRICA] empresas culturais e criativas do SETOR SELECIONADO de PORTE SELECIONADO;
- Quando um porte, um setor e uma UF selecionados: [VALOR SÉRIE HISTÓRICA/MAPA] de empresas DO SETOR SELECIONADO do PORTE SELECIONADO em/na UF; [PORCENTAGEM TREEMAP SETORES] do total de empresas culturais e criativas DO PORTE SELECIONADO em/na UF; [PORCENTAGEM TREEMAP UF] do total de empresas do SETOR SELECIONADO do PORTE SELECIONADO no Brasil.

2. Participação das empresas culturais e criativas no total de empresas
- MANTER COMO ESTÁ.

3. Variação no total de empresas
MANTER COMO ESTÁ.

**Comment by gustavomoller** [comment]
1. Nas variáveis 1, 2, 5, 6 e 7

Quando selecionamos uma UF e e um setor aparece no descritivo EMPRESAS DO SETOR MÚSICA **EM** MINAS GERAIS

![captura de tela 2018-05-13 as 09 29 12](https://user-images.githubusercontent.com/35271320/39967386-81f5c52e-5690-11e8-841c-98ea71da3838.png)
 
Quando troca o ano pela série histórica, aparece o descritivo EMPRESAS DO SETOR DE MÚSICA **DE** MINAS GERAIS

![captura de tela 2018-05-13 as 09 29 21](https://user-images.githubusercontent.com/35271320/39967390-a015bb36-5690-11e8-9731-5842d8bc61b9.png)

O correto é **EM/NO/NA**

2. Variável 2 e 3: Quando seleciona só uma UF, o descritivo deve ser DA UF e não DO BRASIL

3. Variáveis 4, 5, 6 7: colocar DE/DA/DO UF quando selecionada apenas UF

4. Variável 9: quando selecionado um setor e uma UF falta colocar no final um DE/DA/DO UF

![captura de tela 2018-05-13 as 09 36 53](https://user-images.githubusercontent.com/35271320/39967415-33dbf6f0-5691-11e8-9ee9-01c4034d6591.png)

5. Variáveis 10, 11, 12 ,13: o descritivo está errado, está mostrando o descritivo da variável 1

**Comment by leodorna** [comment]
falta corrigir para as variáveis 10,11,12,13
