### ISSUE TITLE
[EXTRAÍDO] Eixo 3 - Variável 3 (BNDES)

### ISSUE THREAD

**Issue by camilacauzzi** [Neccult/atlasOBEC#157]
Atualizar números da V3 (financiamento do BNDES), conforme [arquivo do Excel](https://drive.google.com/file/d/1P_OPCTvNaGFKPgUElw9QwpofcPz_9nJn/view?usp=sharing). Ano de 2017 foi adicionado, porém os dados dos anos anteriores também foram atualizados.

**Comment by xfrigo** [comment]
[v3_sccXano_direto_frigo.txt](https://github.com/Neccult/atlasOBEC/files/1997084/v3_sccXano_direto_frigo.txt)
[v3_sccXano_fundoc_frigo.txt](https://github.com/Neccult/atlasOBEC/files/1997085/v3_sccXano_fundoc_frigo.txt)
[v3_sccXano_indireto_frigo.txt](https://github.com/Neccult/atlasOBEC/files/1997086/v3_sccXano_indireto_frigo.txt)
[v3_sccXano_outros_frigo.txt](https://github.com/Neccult/atlasOBEC/files/1997087/v3_sccXano_outros_frigo.txt)
[v3_sccXano_total_frigo.txt](https://github.com/Neccult/atlasOBEC/files/1997088/v3_sccXano_total_frigo.txt)
