### ISSUE TITLE
[EXTRAIDO] Eixo 3 - V2.1 e V2.2 (Vale-Cultura): correções

### ISSUE THREAD

**Issue by camilacauzzi** [Neccult/atlasOBEC#159]
[OK] PARA TODOS (exceto V2.2. - TRABALHADOR - que não possui setor): série histórica não muda para cada setor (continua sempre o total, mesmo quando um setor é selecionado).

[ok] V2.1. (CONSUMO VIA VALE-CULTURA) - para RECEBEDOR: ao clicar em RECEBEDOR, ambos os "botões" (recebedor e trabalhador) ficam da mesma cor (azul escuro), impossibilitando identificar facilmente qual enfoque está selecionado. Quando clica em trabalhador, fica certo (recebedor fica azul claro e trabalhador fica azul escuro).

[ok] V2.1. (CONSUMO VIA VALE-CULTURA) - tanto para TRABALHADOR quanto para RECEBEDOR: habilitar links da lista de setores (ao lado do gráfico da série histórica), para que os valores relacionados ao setor sejam exibidos no quadro principal.

[ok] V2.1. (CONSUMO VIA VALE-CULTURA) - tanto para TRABALHADOR quanto para RECEBEDOR: valores do mapa não mudam quando é selecionado um setor (o mapa muda para a "cor" do setor, mas continua indicando o valor total - soma de todos os setores).

[ok] V2.1. (CONSUMO VIA VALE-CULTURA) - tanto para TRABALHADOR quanto para RECEBEDOR: primeiro número do quadro principal não está sendo alterado (por exemplo: ao trocar, no menu, para um setor específico, o valor acumulado é trocado, porém o valor do ano continua o valor total para todos os setores). O mesmo ocorre ao selecionar uma UF pelo menu.

____________________________________________________________________________________________________________

[ok] V2.2. (AGENTES DO VALE-CULTURA) - para RECEBEDOR: ao clicar em RECEBEDOR, ambos os "botões" (recebedor e trabalhador) ficam da mesma cor (azul escuro), impossibilitando identificar facilmente qual enfoque está selecionado. Quando clica em trabalhador, fica certo (recebedor fica azul claro e trabalhador fica azul escuro).

[ok] V2.2. (AGENTES DO VALE-CULTURA) - em toda a variável: Tirar os cifrões (R$), pois essa variável não representa dinheiro.

V2.2. (AGENTES DO VALE-CULTURA) - para RECEBEDOR: Atualizar valores acumulados (havia um erro em todos os números da planilha "SCC Acum = Recebedora" no [arquivo em excel](https://drive.google.com/file/d/1CFRkgav2l5wKHkL-WBDp2x_jmxqetRJh/view?usp=sharing))

[ok] V2.2. (AGENTES VALE-CULTURA) - para RECEBEDOR: habilitar links da lista de setores (ao lado do gráfico da série histórica), para que os valores relacionados ao setor sejam exibidos no quadro principal.

[ok] V2.2. (AGENTES VALE-CULTURA) - para RECEBEDOR: valores do mapa não mudam quando é selecionado um setor (o mapa muda para a "cor" do setor, mas continua indicando o valor total - soma de todos os setores).

[ok] V2.2. (AGENTES VALE-CULTURA) - tanto para TRABALHADOR quanto para RECEBEDOR: primeiro número do quadro principal não está sendo alterado (por exemplo: ao trocar, no menu, para um setor específico, o valor acumulado é trocado, porém o valor do ano continua o valor total para todos os setores). O mesmo ocorre ao selecionar uma UF pelo menu.

[ok] V2.2. (AGENTES VALE-CULTURA) - para TRABALHADOR: segundo valor do quadro principal (acumulado) está errado (está aparecendo zerado).

**Comment by xfrigo** [comment]
[v19_sccXAcum_receb_frigo.txt](https://github.com/Neccult/atlasOBEC/files/1997969/v19_sccXAcum_receb_frigo.txt)
