### ISSUE TITLE
[REVISAR] Eixo 2 - Correções de português [variável remuneração média]

### ISSUE THREAD

**Issue by deborawobeto** [Neccult/atlasOBEC#163]
APLICAR AS ALTERAÇÕES RELACIONADAS ABAIXO A TODAS AS VARIÁVEIS:

[OK] [por ocupação] Alterar a descrição "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS NA OCUPAÇÃO ATIVIDADES RELACIONADAS NO BRASIL" para "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS EM ATIVIDADES RELACIONADAS À CULTURA NO BRASIL".
Alterar em todas as UFs
UF Distrito Federal não muda a descrição quando clica, mantem a descrição da UF anterior.
![image](https://user-images.githubusercontent.com/39190809/39925140-e1f3c340-5500-11e8-9c31-934e9394c0e4.png)

[por ocupação] Do mesmo modo, alterar "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS NA OCUPAÇÃO CULTURA NO BRASIL" para "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS EM ATIVIDADES CULTURAIS NO BRASIL".
Alterar em todas as UFs
UF Distrito Federal não muda a descrição quando clica, mantem a descrição da UF anterior. 
![image](https://user-images.githubusercontent.com/39190809/39925172-fe0feafe-5500-11e8-9dab-f77035a83f52.png)

[por setor] Alterar também "DE REMUNERAÇÃO MÉDIA DOS TRABALHADORES DOS SETORES CULTURAIS E CRIATIVOS DO BRASIL" para "DE REMUNERAÇÃO MÉDIA DOS TRABALHADORES NOS SETORES CULTURAIS E CRIATIVOS DO BRASIL".
Alterar em todas as UFs
UF Distrito Federal não muda a descrição quando clica, mantem a descrição da UF anterior.  
![image](https://user-images.githubusercontent.com/39190809/39925063-a0f73606-5500-11e8-975c-75e93b2ad545.png)
  
Na desagregação "idade", alterar "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS NA OCUPAÇÃO CULTURA DE IDADE ENTRE 10 - 17 NO BRASIL" para "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS EM ATIVIDADES CULTURAIS COM IDADE ENTRE 10 - 17 NO BRASIL"
UF Distrito Federal não muda a descrição quando clica, mantem a descrição da UF anterior.  
Alterar em todas as faixas etárias, todas as UFs
![image](https://user-images.githubusercontent.com/39190809/39925456-235ff88e-5502-11e8-89ff-bb6c888adc67.png)

Na desagregação "escolaridade", alterar "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS NA OCUPAÇÃO ATIVIDADES RELACIONADAS DE ESCOLARIDADE SEM INSTRUÇÃO EM SÃO PAULO" para "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS EM ATIVIDADES RELACIONADAS À CULTURA E QUE NÃO POSSUEM INSTRUÇÃO EM SÃO PAULO"
UF Distrito Federal não muda a descrição quando clica, mantem a descrição da UF anterior.
Alterar em todas os níveis de escolaridade, todas as UFs
![image](https://user-images.githubusercontent.com/39190809/39925546-76846324-5502-11e8-90ed-64e1d7f32223.png)

Na desagregação "cor", alterar "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS NA OCUPAÇÃO CULTURA DE ETINIA INDÍGENA NO BRASIL" para "DE REMUNERAÇÃO MÉDIA DOS OCUPADOS DECLARADOS INDÍGENAS EM ATIVIDADES CULTURAIS NO BRASIL".
UF Distrito Federal não muda a descrição quando clica, mantem a descrição da UF anterior.
Alterar em todas as etnias, todas as UFs
![image](https://user-images.githubusercontent.com/39190809/39925881-ce37cbaa-5503-11e8-812d-932e4f8ce43a.png)

**Comment by gustavomoller** [comment]
Quando o setorial está selecionado, os descritivos não aparecem quando alguma desagregação estão selecionada
