### ISSUE TITLE
[REVISAR] Eixo 2 - Correções de português [remuneração por hora]

### ISSUE THREAD

**Issue by deborawobeto** [Neccult/atlasOBEC#172]
[remuneração por hora - setor]
Alterar "POR HORA TRABALHADA DOS SETORES CULTURAIS E CRIATIVOS DO BRASIL" para "POR HORA TRABALHADA NOS SETORES CULTURAIS E CRIATIVOS NO BRASIL".

[remuneração por hora - ocupação]
Alterar "POR HORA TRABALHADA NA OCUPAÇÃO ATIVIDADES RELACIONADAS NO BRASIL" para "POR HORA TRABALHADA EM ATIVIDADES RELACIONADAS À CULTURA NO BRASIL"

Alterar em todas as UFs, todos os anos, todos os setores e todas as desagregações da variável "remuneração por hora trabalhada".

![image](https://user-images.githubusercontent.com/39190809/39927977-654fb92a-550a-11e8-8ba5-8e81bdfd35af.png)

Do mesmo modo, na OCUPAÇÃO CULTURA, alterar "POR HORA TRABALHADA NA OCUPAÇÃO CULTURA NO BRASIL" por "POR HORA TRABALHADA EM OCUPAÇÕES CULTURAIS NO BRASIL"
Alterar em todas as UFs, todos os anos, todos os setores.
![image](https://user-images.githubusercontent.com/39190809/39928113-d10c331e-550a-11e8-90c9-7d654c48f759.png)

Alterar "POR HORA TRABALHADA DO SETOR CULTURA DIGITAL NO BRASIL" por "POR HORA TRABALHADA NO SETOR CULTURA DIGITAL NO BRASIL.
Alterar em todas as UFs, todos os anos, todos os setores.

[nas desagregações] Trocar "POR HORA TRABALHADA DO SETOR CULTURA DIGITAL DE EMPRESAS DE PORTE MICRO NO BRASIL" por "POR HORA TRABALHADA NO SETOR CULTURA DIGITAL DE EMPRESAS DE PORTE MICRO NO BRASIL".
Aplicar a todos os portes, setores, anos e UFs.

Trocar "POR HORA TRABALHADA DO SETOR CULTURA DIGITAL DO SEXO MASCULINO NO BRASIL" por "POR HORA TRABALHADA DOS OCUPADOS DO SEXO MASCULINO NO SETOR CULTURA DIGITAL NO BRASIL"
Aplicar a todos os sexos,setores, anos e UFs.

Trocar "POR HORA TRABALHADA DO SETOR CULTURA DIGITAL DE IDADE ENTRE 10 - 17 NO BRASIL" por "POR HORA TRABALHADA NO SETOR CULTURA DIGITAL NO BRASIL COM IDADE ENTRE 10 - 17".
Aplicar a todas as faixas etárias, setores, anos e UFs.

Trocar "POR HORA TRABALHADA DO SETOR CULTURA DIGITAL DE ESCOLARIDADE SEM INSTRUÇÃO NO BRASIL" por "POR HORA TRABALHADA DO SETOR CULTURA DIGITAL NO BRASIL E QUE NÃO POSSUEM INSTRUÇÃO"

"POR HORA TRABALHADA DO SETOR CULTURA DIGITAL DE ESCOLARIDADE FUNDAMENTAL INCOMPLETO NO BRASIL" por "POR HORA TRABALHADA DO SETOR DE CULTURA DIGITAL NO BRASIL E QUE POSSUEM ESCOLARIDADE DE NÍVEL FUNDAMENTAL INCOMPLETO"

"POR HORA TRABALHADA DO SETOR CULTURA DIGITAL DE ESCOLARIDADE MÉDIO COMPLETO NO BRASIL" por "POR HORA TRABALHADA DO SETOR CULTURA DIGITAL NO BRASIL E QUE POSSUEM  ESCOLARIDADE DE NÍVEL MÉDIO COMPLETO.

Aplicar a todos os níveis de escolaridade, setores, anos e UFs.

![image](https://user-images.githubusercontent.com/39190809/39928831-c33797ae-550c-11e8-8cdf-efa1342e6d24.png)

Alterar "POR HORA TRABALHADA NA OCUPAÇÃO ATIVIDADES RELACIONADAS DE IDADE ENTRE 10 - 17 EM SÃO PAULO" por "POR HORA TRABALHADA EM ATIVIDADES RELACIONADAS À CULTURA EM SÃO PAULO COM IDADE ENTRE 10 - 17.
Aplicar a todas as UFs, anos e faixas etárias
![image](https://user-images.githubusercontent.com/39190809/39929458-7b5c15ac-550e-11e8-8d8e-1e007cfd9f8c.png)

Trocar "POR HORA TRABALHADA NA OCUPAÇÃO CULTURA DE IDADE ENTRE 10 - 17 EM SÃO PAULO" por "POR HORA TRABALHADA EM OCUPAÇÕES CULTURAIS EM SÃO PAULO COM IDADE ENTRE 10 - 17.
Aplicar a todas as UFs, anos e faixas etárias
![image](https://user-images.githubusercontent.com/39190809/39929622-e3c48ae8-550e-11e8-9b50-905036252c0d.png)

Trocar "POR HORA TRABALHADA NA OCUPAÇÃO ATIVIDADES RELACIONADAS DE ESCOLARIDADE SEM INSTRUÇÃO EM SÃO PAULO" por "POR HORA TRABALHADA EM ATIVIDADES RELACIONADAS À CULTURA EM SÃO PAULO e QUE NÃO POSSUEM INSTRUÇÃO.
Aplicar a todas as UFs, anos e escolaridades.
![image](https://user-images.githubusercontent.com/39190809/39929529-a8480e68-550e-11e8-9b84-d43ac40e2e52.png)

Trocar "POR HORA TRABALHADA NA OCUPAÇÃO CULTURA DE ETINIA INDÍGENA EM SÃO PAULO" por "POR HORA TRABALHADA DOS DECLARADOS INDÍGENAS EM OCUPAÇÕES CULTURAIS EM SÃO PAULO"
Aplicar a todas as UFs, anos e etnias.
![image](https://user-images.githubusercontent.com/39190809/39930014-f278ac3a-550f-11e8-8ede-c6daab93f259.png)

**Comment by gustavomoller** [comment]
Mesmo problema da remuneração média, sem descritivo da desagregação quando nenhum setor está selecionado
