### ISSUE TITLE
[PARCIAL] Eixo 2 - Total de ocupados - recorte setorial

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#184]
- Onde se lê DO TOTAL DE TRABALHADORES DO SETOR EDITORIAL DE SÃO PAULO, deveria ser DO TOTAL DE TRABALHADORES DOS SETORES CULTURAIS E CRIATIVOS DE SÃO PAULO

- Da mesma maneira, onde se lê DO TOTAL DE TRABALHADORES DO SETOR EDITORIAL DO BRASIL. Quanto a este segundo número, ele não faz sentido. Verificar base de dados

![captura de tela 2018-05-12 as 16 11 30](https://user-images.githubusercontent.com/35271320/39960835-3a5ee62c-5600-11e8-9146-b2ef702cf4c3.png)

**Comment by leodorna** [comment]
Botei os dados 2015-2016 e corrigi as descrições.

**Comment by leodorna** [comment]
Não muda a porcentagem quando seleciona uma desagregação.
