### ISSUE TITLE
[EXTRAIR] Eixo 4 - Variável PARTICIPAÇÃO NO COMÉRCIO EXTERIOR TOTAL

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#188]
Verificar os valores para serviços e parceiros. Não é possível uma participação de 105%.

![captura de tela 2018-05-12 as 16 58 00](https://user-images.githubusercontent.com/35271320/39961122-d743770a-5605-11e8-896b-5c5c5224258c.png)

**Comment by leodorna** [comment]
a larissa já enviou os dados certos se não me engano. tem que extrair

**Comment by xfrigo** [comment]
[v2_OCEANIA_imp.txt](https://github.com/Neccult/atlasOBEC/files/1998846/v2_OCEANIA_imp.txt)
[v2_OCEANIA_exp.txt](https://github.com/Neccult/atlasOBEC/files/1998847/v2_OCEANIA_exp.txt)
[v2_MUNDO_imp.txt](https://github.com/Neccult/atlasOBEC/files/1998848/v2_MUNDO_imp.txt)
[v2_MUNDO_exp.txt](https://github.com/Neccult/atlasOBEC/files/1998849/v2_MUNDO_exp.txt)
[v2_EUROPA_imp.txt](https://github.com/Neccult/atlasOBEC/files/1998850/v2_EUROPA_imp.txt)
[v2_EUROPA_exp.txt](https://github.com/Neccult/atlasOBEC/files/1998851/v2_EUROPA_exp.txt)
[v2_ASIA_imp.txt](https://github.com/Neccult/atlasOBEC/files/1998852/v2_ASIA_imp.txt)
[v2_ASIA_exp.txt](https://github.com/Neccult/atlasOBEC/files/1998853/v2_ASIA_exp.txt)
[v2_AMERICA SUL CENTRAL_imp.txt](https://github.com/Neccult/atlasOBEC/files/1998854/v2_AMERICA.SUL.CENTRAL_imp.txt)
[v2_AMERICA SUL CENTRAL_exp.txt](https://github.com/Neccult/atlasOBEC/files/1998855/v2_AMERICA.SUL.CENTRAL_exp.txt)
[v2_AMERICA NORTE_imp.txt](https://github.com/Neccult/atlasOBEC/files/1998856/v2_AMERICA.NORTE_imp.txt)
[v2_AMERICA NORTE_exp.txt](https://github.com/Neccult/atlasOBEC/files/1998857/v2_AMERICA.NORTE_exp.txt)
[v2_AFRICA_imp.txt](https://github.com/Neccult/atlasOBEC/files/1998858/v2_AFRICA_imp.txt)
[v2_AFRICA_exp.txt](https://github.com/Neccult/atlasOBEC/files/1998859/v2_AFRICA_exp.txt)
