### ISSUE TITLE
Eixo 2 - Variável 3 - Remuneração Média

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#191]
O botão TODOS não está funcionando no treemap

![captura de tela 2018-05-13 as 10 00 58](https://user-images.githubusercontent.com/35271320/39967588-a5a75862-5694-11e8-9fb6-474b25f87528.png)

**Comment by xfrigo** [comment]
Não entendi, não há treemap nessa variável. 
O botão todos só é para funcionar quando anteoriormente há algum setor selecionado.
Favor, levando isso em consideração, testsar novamente.
