### ISSUE TITLE
[PARCIAL] EIXO 2 - IHH e C4 - Ocupacional

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#196]
A informação nas quatro variáveis está repetida nos boxes das séries históricas

![captura de tela 2018-05-13 as 16 23 15](https://user-images.githubusercontent.com/35271320/39970951-067b7da0-56ca-11e8-94f8-3c1c43b4ec1f.png)

**Comment by xfrigo** [comment]
Os dados para Atividades Relacionadas e Cultura estão idênticos no banco de dados.
É necessário verificar se há erro na extração ou nas planilhas.

**Comment by leodorna** [comment]
Acho que na verdade estão funcionando sim, só tem que mudar as legendas
