### ISSUE TITLE
Eixo 2 - Descrição das variáveis

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#25]
Conforme anexo

[NECCULT - 2018 - ATLAS - Eixo 02 - Descrição Variáveis Plataforma.docx](https://github.com/Neccult/atlasOBEC/files/1790015/NECCULT.-.2018.-.ATLAS.-.Eixo.02.-.Descricao.Variaveis.Plataforma.docx)

**Comment by leodorna** [comment]
Olá, não sei se tem algum problema, mas tem algumas descrições que não bate com o nome da variável. Por exemplo, a descrição da variável "Total de Trabalhadores" (variável 1) é "A variável total de ocupados... ".

**Comment by gustavomoller** [comment]
Alterações nas descrições

Variável 1 - A variável total de trabalhadores retrata o total de indivíduos envolvidos com atividades produtivas ligadas aos Setores Culturais e Criativos ou às Ocupações Culturais e Criativas, permitindo que sejam avaliadas estatísticas do trabalho formal e informal e suas características principais. A quantidade de trabalhadores em atividades do campo cultural pode retratar o perfil da força de trabalho na cultura no Brasil.

Variável 2 - A variável participação no emprego retrata o peso do mercado de trabalho no campo cultural e criativo em relação ao nível geral de atividade no país. Estima-se a taxa de pessoas ocupadas em Setores Culturais e Criativos ou Ocupações Culturais e Criativas diante do mercado geral de trabalho no país.

Variável 6 - trocar o nome de Jornada de Trabalho por Jornada de trabalho média

Variável 7 - A variável massa salarial representa a soma de todas as remunerações pagas aos ocupados durante cada ano de análise. Estima-se a soma dos rendimentos de todos os ocupados em atividades culturais e para os trabalhadores ligados aos Setores Culturais e Criativos ou às Ocupações Culturais e Criativas, em que mudanças na massa salarial podem representar variações os níveis de atividade.

Variável 9 - A variável razão entre a massa salarial e o valor adicionado pelos Setores Culturais e Criativos permite a avaliação do quanto o total de salários mantém relação com o valor adicionado nos Setores Culturais e Criativos no país. 

Variável 13 - A variável razão de concentração da massa salarial (C4) retrata a distribuição da Massa Salarial dentre os Setores Culturais e Criativos, as Ocupações Culturais e Criativas e as unidades federativas. Representa a participação relativa dos quatro maiores valores em relação aos totais analisados.

Variável 15 - Mudar o nome da variável para IHH DA MASSA SALARIAL : A variável índice Herfindal-Hirschman (IHH) de concentração da massa salarial mostra a maneira como os rendimentos estão distribuídos dentre o total de Setores Culturais e Criativos, Ocupações Culturais e Criativas e unidades federativas.
