### ISSUE TITLE
Eixo 3 - Extrações

### ISSUE THREAD

**Issue by mtfrigo** [Neccult/atlasOBEC#281]
Variável 1: ok
Atualizar 2017.
[link V1](https://drive.google.com/open?id=1SMxWt_L4Y9YbYb_kUFpdpvfI8cDQrrcQ)

Variável 4: ok
adicionar dados para 2017. o restante continua igual. 
[link 4](https://drive.google.com/open?id=1FU6CjNJlJacdZ4myJfE7LcC3SNLSL1wp)

Variável 5: ok
adicionar dados para 2017. o restante continua igual. 
[link 5](https://drive.google.com/open?id=1v4d1LKiLxcvbCGbSBNgUmND6lufgjsbv)

Variável 7: ok

Atualizar valores de 2016, que estão errados. O dos outros anos está certo.
[link V7](https://drive.google.com/open?id=1GXmB4MOScU-lepjJ9K-mPjtBhb8mvhWL)

Variável 11: ok

Trocar valor de 2016 (foi atualizado na planilha) e adicionar ano de 2017 (foi adicionado na planilha): [link 11](https://drive.google.com/open?id=1SS6J7e5fjxUupoHpVsWW23TgFhIjHXDp)

Variável 12:  ok

Trocar valor de 2016 (foi atualizado na planilha) e adicionar ano de 2017 (foi adicionado na planilha): 
[link 12](https://drive.google.com/open?id=1Fl6iqkL0K69NVfwKY6O6Zqggct6hAdwz)

Variável 13: ok

Atualizar todos os valores de 2016. O restante está correto. [link V13](https://drive.google.com/open?id=1iVx0A3AEG9yki_o9itFrm0BirMgcEFwo)

Variável 14: ok

Atualizar todos os valores de 2016. O restante está correto. [link v14](https://drive.google.com/open?id=1SwLV2SRlKvvdQ7zBD_V98_nT01YfKg6L)

Variável 15: ok
foram adicionados os valores para 2017 no quesito **mecenato, FNC e total** (o restante continua igual):
[lnik 15](https://drive.google.com/open?id=1zwKsnOLEayZGWqKP88JoFzbSASEyzvdd)

Variável 16: ok
foram adicionados os valores para 2017 no quesito **mecenato, FNC e total** (o restante continua igual): 
[link 16](https://drive.google.com/open?id=1OFcPEvglHN46_kC205kODbsfz1tuuBSW)

**CONFERIR**

Variável 10:
[link v10](https://drive.google.com/open?id=1PgaCUU7NZs1MjeK16K6vL2d37QXAiBpT)

**Comment by leodorna** [comment]
Anotação:
Variável 7 do eixo 3 está multiplicada por 100 no banco de dados
