### ISSUE TITLE
Eixo 1 - Porcentagem das receitas totais brutas nao batem quando selecionado o setor

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#34]
![image](https://user-images.githubusercontent.com/35271320/38578742-31849846-3cdb-11e8-92d5-2637c9e34e3a.png)

**Comment by xfrigo** [comment]
Ao verificar a variável não notei porcentagens erradas. Provavelmente bug corrigido ou bug do contexto.
