### ISSUE TITLE
Eixo I - Variável total de empresas - porcentagem setor

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#7]
Inserir o nome do setor no box de dados quando algum setor estiver selecionado nesta variável. 

![screenshot_1](https://user-images.githubusercontent.com/35271320/35812785-1a42127e-0a79-11e8-86fc-0d4a1c1899ea.png)

**Comment by esanguinet** [comment]
## legenda campo "Dados"

1. Ao selecionar o filtro "porte", a legenda mostra sempre "Brasil", independente da UF selecionada.
** além da desagregação "porte" nem sempre aparecer.
