### ISSUE TITLE
Eixo 4 - Relação com VA

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#74]
1. Colocar em porcentagem

2. Tirar a opção do tipo Saldo Comercial]

3.  Mostrar o valor da variável no gráfico de rosca e não o valor relativo

**Comment by leodorna** [comment]
Sobre "Mostrar o valor da variável no gráfico de rosca e não o valor relativo":
É para manter a proporção de cada um, mas mudar o texto?
