### ISSUE TITLE
Descrições dos dados

### ISSUE THREAD

**Issue by xfrigo** [Neccult/atlasOBEC#89]
Eixo 3:
Variável - Fomento Público Estadual à cultura;
Variável - Participação do financiamento público nas contas públicas.

**Comment by gustavomoller** [comment]
Participação do financiamento público nas contas públicas.
(esquerda) 0,27% de despesa do MinC em relação ao total da arrecadação federal
(direita) 0,49% do total de financiamento federal via FNC e mecenato em relação ao total da arrecadação federal
