### ISSUE TITLE
Eixo 1 - Variável PARTICIPAÇÃO DAS EMPRESAS CULTURAIS E CRIATIVAS NO TOTAL DE EMPRESAS - Treemap SCC

### ISSUE THREAD

**Issue by gustavomoller** [Neccult/atlasOBEC#9]
Habilitar visualização da seguinte maneitra:

1 - Quando não há UF/Setor selecionado, utilizar dados totais dos setores em relação ao Brasil. Eduardo/Artur irão passar.

2 - Quando há UF/setor selecionado, utilizar os dados do mapa.

**Comment by esanguinet** [comment]
## Caixa "Dados"

1. Mostrar só um valor (excluir o segundo percentual). Deixar só o primeiro (que, na verdade, é um percentual);
2. Os valores estão multiplicados duas vezes por 100. Ex.: Em 2014, o correto é 2,75% (atualmente está 275,34)


## Treemap SCC
1. Quando não há UF selecionada, mostrar Treemap SCC para o "total de empresas da economia brasileira". Em anexo os valores relativos (deve-se multiplicar por 100 para serem expressos em percentuais)
[V2 - Eixo 1 - Complemento Treemap SCC.xlsx](https://github.com/Neccult/atlasOBEC/files/1695982/V2.-.Eixo.1.-.Complemento.Treemap.SCC.xlsx)

2. Quando não há UF selecionada, mostrar Treemap SCC para o "total de empresas da UF selecionado". Os valores percentuais são os mesmos já enviados.
